import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';

export const metadata: Metadata = {
  title: 'Web Printer System',
  description: 'Generated by nextjs',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="https://www.hp-smart.cn/favicons/favicon.ico"></link>
      </head>
      <body className="flex flex-col  w-full h-full min-w-80 max-w-2xl m-auto h-screen relative">
        <AntdRegistry>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
